# Generated by Django 5.1.6 on 2025-02-10 03:02

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
